services:
  - type: web
    name: medusa-production
    runtime: node
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm run deploy:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_zpjwXBPl96Si@ep-winter-shape-acyx74fh-pooler.sa-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require
      - key: JWT_SECRET
        value: 6f03a2a0b822da8660e63e3fc557a999ad08927579ff2ace45f0a5c7d8ac738ee3a94c60ea843cc1e8ad7fccc03189408dc77ba98198a40314a393857627902b
      - key: COOKIE_SECRET
        value: 32245595c98c836f7c833265699d222072297d105ccd109e06dacc8a382ebf8e29e05486b81f973e55f728b7cf5bea0bcf6e4a2c998f6bfb823c505052a57de2
      - key: ADMIN_JWT_SECRET
        value: b55d968d1368d0582966311ea6e2400876a30fe330a5384c830c7d1ed0b6fc93eaff707336e446e29db1fd097707002124580dd791c8255801dd2dabea67839d
      - key: CORS_ORIGIN
        value: https://store.optivoo.com
    healthCheckPath: /health
    disk:
      name: medusa-disk
      size: 1GB
      mount: /opt/render/project/src/uploads